[env]
# Application settings
REDIRECT_ENVIRONMENT = "development"
REDIRECT_API_KEY = "env123"
REDIRECT_ENABLE_RATELIMITER = "false"

# Database settings
REDIRECT_DB_DSN = "postgres://postgres:password@172.40.0.10/redirect?sslmode=disable"
REDIRECT_DB_MAX_OPEN_CONNECTIONS = 25
REDIRECT_DB_MAX_IDLE_CONNECTIONS = 25
REDIRECT_DB_MAX_IDLE_TIME = "10m"

# Webserver settings
REDIRECT_LISTEN_ADDRESS = "127.0.0.1"
REDIRECT_LISTEN_PORT = 4000

[tools]
golangci-lint = "1.59.1"
