#file: noinspection SpellCheckingInspection
services:
  db:
    image: postgres:16.3-alpine
    container_name: postgres16
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: redirect
    profiles:
      - dev
      - simple-prod
      - migration
    volumes:
      - redirectdata:/var/lib/postgresql/data
    networks:
      redirect:
        ipv4_address: 172.40.0.10
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 30s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M

  goredirect:
    image: ghcr.io/pythoninja/go-redirect:latest
    container_name: go-redirect
    restart: unless-stopped
    environment:
      REDIRECT_ENVIRONMENT: production
      REDIRECT_DB_DSN: postgres://postgres:password@172.40.0.10/redirect?sslmode=disable
    profiles:
      - simple-prod
    networks:
      redirect:
        ipv4_address: 172.40.0.20
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
    depends_on:
      db:
        condition: service_healthy

  migration:
    image: migrate/migrate:v4.17.1
    container_name: migrate
    environment:
      REDIRECT_DB_DSN: postgres://postgres:password@172.40.0.10/redirect?sslmode=disable
    profiles:
      - migration
    command: ["-path", "/migrations", "-database", "$REDIRECT_DB_DSN", "up"]
    volumes:
      - "${PWD}/migrations:/migrations"
    networks:
      redirect:
        ipv4_address: 172.40.0.50
    depends_on:
      db:
        condition: service_healthy

networks:
  redirect:
    name: redirect
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.40.0.0/16
volumes:
  redirectdata:
