name: golangci-lint
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    paths:
      - '.github/workflows/**'
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'

permissions:
  contents: read

env:
  GO_VERSION: '1.22.4'
  GOLANGCI_LINT_VERSION: 'v1.59.1'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

  go-test:
    name: test
    runs-on: ubuntu-latest

    needs:
      - golangci

    strategy:
      max-parallel: 3
      matrix:
        go-version: [ '1.22.2', '1.22.3', '1.22.4' ]

    steps:
      - uses: actions/checkout@v4
      - name: "Set up Go"
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go mod tidy
      - name: Build
        run: go build -v ./cmd/api
      - name: Test
        run: go test ./...
